In [2]:
import numpy as np
import pandas as pd

In [3]:
path_to_data = 'NTSB avall file dataset_1.xlsx'
ntsb=pd.ExcelFile(path_to_data)
ntsb1 = pd.read_excel(ntsb, 'Aircraft related')
ntsb2 = pd.read_excel(ntsb, 'Event related')
ntsb3 = pd.read_excel(ntsb, 'Findings')
ntsb4 = pd.read_excel(ntsb, 'Engines')
ntsb5 = pd.read_excel(ntsb, 'Flight_Crew')

In [4]:
print(len(ntsb1))
print(len(ntsb2))
print(len(ntsb3))
print(len(ntsb4))
print(len(ntsb5))

27844
27410
65093
27843
28392

In [5]:
ntsb1 = pd.read_excel(path_to_data, sheet_name='Aircraft related', usecols=['ev_id','cert_max_gr_wt','acft_category','homebuilt','afm_hrs_last_insp','damage'])
ntsb2 = pd.read_excel(path_to_data, sheet_name='Event related', usecols=['ev_id','ev_dow', 'ev_time','ev_year', 'ev_month','ev_nr_apt_loc',
       'apt_dist','apt_elev','light_cond', 'sky_cond_nonceil','altimeter',
       'sky_nonceil_ht', 'sky_ceil_ht', 'sky_cond_ceil', 'vis_sm', 'wx_temp', 'wx_dew_pt', 'wind_dir_deg','wind_vel_kts', 'dec_latitude', 'dec_longitude', 'gust_kts','ev_highest_injury','wx_cond_basic','dec_latitude', 'dec_longitude'])
ntsb3 = pd.read_excel(path_to_data, sheet_name='Findings', usecols=['ev_id','Cause_Factor'])
ntsb4 = pd.read_excel(path_to_data, sheet_name='Engines', usecols=['ev_id','eng_type'])
ntsb5 = pd.read_excel(path_to_data, sheet_name='Flight_Crew', usecols=['ev_id','crew_age','med_certf','med_crtf_vldty','crew_tox_perf','crew_no'])

In [6]:
dataframes = [ntsb1, ntsb2, ntsb3, ntsb4, ntsb5]
merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = pd.merge(merged_df, df, on='ev_id', how='inner')
print(merged_df)

                ev_id damage  cert_max_gr_wt acft_category homebuilt  \
0      20080107X00026   MINR          2400.0           AIR         N
1      20080107X00026   MINR          2400.0           AIR         N
2      20080107X00026   MINR          2400.0           AIR         N
3      20080107X00026   MINR          2400.0           AIR         N
4      20080107X00026   MINR          2400.0           AIR         N
...               ...    ...             ...           ...       ...
94099  20240531194353   SUBS          3600.0           AIR         N
94100  20240531194353   SUBS          3600.0           AIR         N
94101  20240531194353   SUBS          3600.0           AIR         N
94102  20240603194359   SUBS          2500.0          HELI         N
94103  20240603194359   SUBS          2500.0          HELI         N

       afm_hrs_last_insp ev_dow  ev_time  ev_year  ev_month  ...  \
0                   75.0     Tu   2230.0     2008         1  ...
1                   75.0     Tu   2230.0     2008         1  ...
2                   75.0     Tu   2230.0     2008         1  ...
3                   75.0     Tu   2230.0     2008         1  ...
4                   75.0     Tu   2230.0     2008         1  ...
...                  ...    ...      ...      ...       ...  ...
94099                NaN     Th   1617.0     2024         5  ...
94100                NaN     Th   1617.0     2024         5  ...
94101                NaN     Th   1617.0     2024         5  ...
94102                NaN     Su   1815.0     2024         6  ...
94103                NaN     Su   1815.0     2024         6  ...

      wx_cond_basic  dec_latitude  dec_longitude Cause_Factor eng_type  \
0               VMC     38.223888    -122.449722            C      REC
1               VMC     38.223888    -122.449722            C      REC
2               VMC     38.223888    -122.449722            C      REC
3               VMC     38.223888    -122.449722            C      REC
4               VMC     38.223888    -122.449722            C      REC
...             ...           ...            ...          ...      ...
94099           VMC     27.642597     -82.519917          NaN      NaN
94100           VMC     27.642597     -82.519917          NaN      NaN
94101           VMC     27.642597     -82.519917          NaN      NaN
94102           VMC     36.937020     -88.229340          NaN      NaN
94103           VMC     36.937020     -88.229340          NaN      NaN

       crew_no  crew_age med_certf  med_crtf_vldty  crew_tox_perf
0            1      56.0       CL3             WWL              N
1            1      70.0       CL3             WWL              N
2            1      56.0       CL3             WWL              N
3            1      70.0       CL3             WWL              N
4            1      56.0       CL3             WWL              N
...        ...       ...       ...             ...            ...
94099        1      62.0       CL3            WOWL            NaN
94100        1      62.0       CL3            WOWL            NaN
94101        1      62.0       CL3            WOWL            NaN
94102        1      86.0      NONE             NaN            NaN
94103        1      86.0      NONE             NaN            NaN

[94104 rows x 36 columns]

In [7]:
filtered_df = merged_df[(merged_df['acft_category'] == "AIR")]
print(filtered_df)

                ev_id damage  cert_max_gr_wt acft_category homebuilt  \
0      20080107X00026   MINR          2400.0           AIR         N
1      20080107X00026   MINR          2400.0           AIR         N
2      20080107X00026   MINR          2400.0           AIR         N
3      20080107X00026   MINR          2400.0           AIR         N
4      20080107X00026   MINR          2400.0           AIR         N
...               ...    ...             ...           ...       ...
94097  20240526194310   SUBS          3600.0           AIR         N
94098  20240526194310   SUBS          3600.0           AIR         N
94099  20240531194353   SUBS          3600.0           AIR         N
94100  20240531194353   SUBS          3600.0           AIR         N
94101  20240531194353   SUBS          3600.0           AIR         N

       afm_hrs_last_insp ev_dow  ev_time  ev_year  ev_month  ...  \
0                   75.0     Tu   2230.0     2008         1  ...
1                   75.0     Tu   2230.0     2008         1  ...
2                   75.0     Tu   2230.0     2008         1  ...
3                   75.0     Tu   2230.0     2008         1  ...
4                   75.0     Tu   2230.0     2008         1  ...
...                  ...    ...      ...      ...       ...  ...
94097                NaN     Mo   1730.0     2024         3  ...
94098                NaN     Mo   1730.0     2024         3  ...
94099                NaN     Th   1617.0     2024         5  ...
94100                NaN     Th   1617.0     2024         5  ...
94101                NaN     Th   1617.0     2024         5  ...

      wx_cond_basic  dec_latitude  dec_longitude Cause_Factor eng_type  \
0               VMC     38.223888    -122.449722            C      REC
1               VMC     38.223888    -122.449722            C      REC
2               VMC     38.223888    -122.449722            C      REC
3               VMC     38.223888    -122.449722            C      REC
4               VMC     38.223888    -122.449722            C      REC
...             ...           ...            ...          ...      ...
94097           VMC     33.227006     -84.274975          NaN      NaN
94098           VMC     33.227006     -84.274975          NaN      NaN
94099           VMC     27.642597     -82.519917          NaN      NaN
94100           VMC     27.642597     -82.519917          NaN      NaN
94101           VMC     27.642597     -82.519917          NaN      NaN

       crew_no  crew_age med_certf  med_crtf_vldty  crew_tox_perf
0            1      56.0       CL3             WWL              N
1            1      70.0       CL3             WWL              N
2            1      56.0       CL3             WWL              N
3            1      70.0       CL3             WWL              N
4            1      56.0       CL3             WWL              N
...        ...       ...       ...             ...            ...
94097        1      39.0       CL2            WOWL            NaN
94098        1      39.0       CL2            WOWL            NaN
94099        1      62.0       CL3            WOWL            NaN
94100        1      62.0       CL3            WOWL            NaN
94101        1      62.0       CL3            WOWL            NaN

[80975 rows x 36 columns]

In [8]:
output_filename = 'dataset2.csv'
filtered_df.to_csv(output_filename, index=False)
print(f"Data saved to {output_filename}")

Data saved to dataset2.csv

In [9]:
count_Y = len(merged_df[merged_df['homebuilt'] == "Y"])

In [10]:
print(count_Y)

10560

In [11]:
filtered_df_1 = filtered_df[(filtered_df['homebuilt'] == "N")]
print(filtered_df_1)

                ev_id damage  cert_max_gr_wt acft_category homebuilt  \
0      20080107X00026   MINR          2400.0           AIR         N
1      20080107X00026   MINR          2400.0           AIR         N
2      20080107X00026   MINR          2400.0           AIR         N
3      20080107X00026   MINR          2400.0           AIR         N
4      20080107X00026   MINR          2400.0           AIR         N
...               ...    ...             ...           ...       ...
94097  20240526194310   SUBS          3600.0           AIR         N
94098  20240526194310   SUBS          3600.0           AIR         N
94099  20240531194353   SUBS          3600.0           AIR         N
94100  20240531194353   SUBS          3600.0           AIR         N
94101  20240531194353   SUBS          3600.0           AIR         N

       afm_hrs_last_insp ev_dow  ev_time  ev_year  ev_month  ...  \
0                   75.0     Tu   2230.0     2008         1  ...
1                   75.0     Tu   2230.0     2008         1  ...
2                   75.0     Tu   2230.0     2008         1  ...
3                   75.0     Tu   2230.0     2008         1  ...
4                   75.0     Tu   2230.0     2008         1  ...
...                  ...    ...      ...      ...       ...  ...
94097                NaN     Mo   1730.0     2024         3  ...
94098                NaN     Mo   1730.0     2024         3  ...
94099                NaN     Th   1617.0     2024         5  ...
94100                NaN     Th   1617.0     2024         5  ...
94101                NaN     Th   1617.0     2024         5  ...

      wx_cond_basic  dec_latitude  dec_longitude Cause_Factor eng_type  \
0               VMC     38.223888    -122.449722            C      REC
1               VMC     38.223888    -122.449722            C      REC
2               VMC     38.223888    -122.449722            C      REC
3               VMC     38.223888    -122.449722            C      REC
4               VMC     38.223888    -122.449722            C      REC
...             ...           ...            ...          ...      ...
94097           VMC     33.227006     -84.274975          NaN      NaN
94098           VMC     33.227006     -84.274975          NaN      NaN
94099           VMC     27.642597     -82.519917          NaN      NaN
94100           VMC     27.642597     -82.519917          NaN      NaN
94101           VMC     27.642597     -82.519917          NaN      NaN

       crew_no  crew_age med_certf  med_crtf_vldty  crew_tox_perf
0            1      56.0       CL3             WWL              N
1            1      70.0       CL3             WWL              N
2            1      56.0       CL3             WWL              N
3            1      70.0       CL3             WWL              N
4            1      56.0       CL3             WWL              N
...        ...       ...       ...             ...            ...
94097        1      39.0       CL2            WOWL            NaN
94098        1      39.0       CL2            WOWL            NaN
94099        1      62.0       CL3            WOWL            NaN
94100        1      62.0       CL3            WOWL            NaN
94101        1      62.0       CL3            WOWL            NaN

[71336 rows x 36 columns]

In [12]:
df = filtered_df_1.drop_duplicates().reset_index(drop=True)

In [13]:
output_filename = 'dataset3.csv'
df.to_csv(output_filename, index=False)
print(f"Data saved to {output_filename}")

Data saved to dataset3.csv

In [14]:
filtered_df = df[df['damage'].isin(['MINR', 'SUBS','DEST'])]
filtered_df = filtered_df.drop_duplicates(subset=['ev_id', 'damage'])
filtered_df = filtered_df.reset_index(drop=True)
print(filtered_df)

                ev_id damage  cert_max_gr_wt acft_category homebuilt  \
0      20080107X00026   MINR          2400.0           AIR         N
1      20080109X00036   SUBS          2850.0           AIR         N
2      20080115X00051   SUBS          1670.0           AIR         N
3      20080115X00047   SUBS          2550.0           AIR         N
4      20080116X00063   SUBS          7368.0           AIR         N
...               ...    ...             ...           ...       ...
15515  20240516194270   SUBS          2800.0           AIR         N
15516  20240519194280   SUBS         12500.0           AIR         N
15517  20240520194283   SUBS          2200.0           AIR         N
15518  20240526194310   SUBS          3600.0           AIR         N
15519  20240531194353   SUBS          3600.0           AIR         N

       afm_hrs_last_insp ev_dow  ev_time  ev_year  ev_month  ...  \
0                   75.0     Tu   2230.0     2008         1  ...
1                    NaN     Tu   2200.0     2008         1  ...
2                    NaN     We   2230.0     2008         1  ...
3                   54.0     Sa   2045.0     2008         1  ...
4                   27.0     Sa   1743.0     2008         1  ...
...                  ...    ...      ...      ...       ...  ...
15515                NaN     Fr   1630.0     2024         5  ...
15516               19.0     Sa   1830.0     2024         5  ...
15517                7.6     We   2230.0     2024         5  ...
15518                NaN     Mo   1730.0     2024         3  ...
15519                NaN     Th   1617.0     2024         5  ...

      wx_cond_basic  dec_latitude  dec_longitude Cause_Factor eng_type  \
0               VMC     38.223888    -122.449722            C      REC
1               VMC     29.506111     -95.476669            F      REC
2               VMC     40.451667    -105.001113            C      REC
3               VMC     38.202220     -77.587501            F      REC
4               VMC     57.750556    -152.468612            C      REC
...             ...           ...            ...          ...      ...
15515           VMC     45.878111    -111.569440          NaN      NaN
15516           VMC     40.941560     -82.863440          NaN      NaN
15517           VMC     29.727974     -96.060159          NaN      NaN
15518           VMC     33.227006     -84.274975          NaN      NaN
15519           VMC     27.642597     -82.519917          NaN      NaN

       crew_no  crew_age med_certf  med_crtf_vldty  crew_tox_perf
0            1      56.0       CL3             WWL              N
1            1      54.0       CL3             WWL              N
2            1      36.0       CL3            WOWL              N
3            1      57.0       CL3            WOWL              N
4            1      50.0       CL1            WOWL              Y
...        ...       ...       ...             ...            ...
15515        1      77.0       CL3            WOWL            NaN
15516        1      51.0       CL1            WOWL            NaN
15517        1      56.0       CL3             WWL            NaN
15518        1      39.0       CL2            WOWL            NaN
15519        1      62.0       CL3            WOWL            NaN

[15520 rows x 36 columns]

In [15]:
output_filename = 'dataset4.csv'
filtered_df.to_csv(output_filename, index=False)
print(f"Data saved to {output_filename}")

Data saved to dataset4.csv

In [16]:
path_to_data = 'dataset4_(1).xlsx'
df = pd.read_excel(path_to_data)  
df.dropna(subset=['Severity_class'])

,ev_id,damage,ev_highest_injury,Severity_class,cert_max_gr_wt,acft_category,homebuilt,afm_hrs_last_insp,ev_dow,ev_time,...,wx_cond_basic,dec_latitude,dec_longitude,Cause_Factor,eng_type,crew_no,crew_age,med_certf,med_crtf_vldty,crew_tox_perf
0,20080107X00026,MINR,NONE,MINR-NONE,2400.0,AIR,N,75.0,Tu,2230.0,...,VMC,38.223888,-122.449722,C,REC,1,56.0,CL3,WWL,N
1,20080109X00036,SUBS,NONE,SUBS-NONE,2850.0,AIR,N,NaN,Tu,2200.0,...,VMC,29.506111,-95.476669,F,REC,1,54.0,CL3,WWL,N
2,20080115X00051,SUBS,NONE,SUBS-NONE,1670.0,AIR,N,NaN,We,2230.0,...,VMC,40.451667,-105.001113,C,REC,1,36.0,CL3,WOWL,N
3,20080115X00047,SUBS,MINR,SUBS-MINR,2550.0,AIR,N,54.0,Sa,2045.0,...,VMC,38.202220,-77.587501,F,REC,1,57.0,CL3,WOWL,N
4,20080116X00063,SUBS,FATL,SUBS-FATL,7368.0,AIR,N,27.0,Sa,1743.0,...,VMC,57.750556,-152.468612,C,REC,1,50.0,CL1,WOWL,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15515,20240516194270,SUBS,NONE,SUBS-NONE,2800.0,AIR,N,NaN,Fr,1630.0,...,VMC,45.878111,-111.569440,NaN,NaN,1,77.0,CL3,WOWL,NaN
15516,20240519194280,SUBS,MINR,SUBS-MINR,12500.0,AIR,N,19.0,Sa,1830.0,...,VMC,40.941560,-82.863440,NaN,NaN,1,51.0,CL1,WOWL,NaN
15517,20240520194283,SUBS,NONE,SUBS-NONE,2200.0,AIR,N,7.6,We,2230.0,...,VMC,29.727974,-96.060159,NaN,NaN,1,56.0,CL3,WWL,NaN
15518,20240526194310,SUBS,NONE,SUBS-NONE,3600.0,AIR,N,NaN,Mo,1730.0,...,VMC,33.227006,-84.274975,NaN,NaN,1,39.0,CL2,WOWL,NaN
15519,20240531194353,SUBS,NONE,SUBS-NONE,3600.0,AIR,N,NaN,Th,1617.0,...,VMC,27.642597,-82.519917,NaN,NaN,1,62.0,CL3,WOWL,NaN

In [17]:
df.loc[:, df.nunique() > 1]

,ev_id,damage,ev_highest_injury,Severity_class,cert_max_gr_wt,afm_hrs_last_insp,ev_dow,ev_time,ev_year,ev_month,...,wx_cond_basic,dec_latitude,dec_longitude,Cause_Factor,eng_type,crew_no,crew_age,med_certf,med_crtf_vldty,crew_tox_perf
0,20080107X00026,MINR,NONE,MINR-NONE,2400.0,75.0,Tu,2230.0,2008,1,...,VMC,38.223888,-122.449722,C,REC,1,56.0,CL3,WWL,N
1,20080109X00036,SUBS,NONE,SUBS-NONE,2850.0,NaN,Tu,2200.0,2008,1,...,VMC,29.506111,-95.476669,F,REC,1,54.0,CL3,WWL,N
2,20080115X00051,SUBS,NONE,SUBS-NONE,1670.0,NaN,We,2230.0,2008,1,...,VMC,40.451667,-105.001113,C,REC,1,36.0,CL3,WOWL,N
3,20080115X00047,SUBS,MINR,SUBS-MINR,2550.0,54.0,Sa,2045.0,2008,1,...,VMC,38.202220,-77.587501,F,REC,1,57.0,CL3,WOWL,N
4,20080116X00063,SUBS,FATL,SUBS-FATL,7368.0,27.0,Sa,1743.0,2008,1,...,VMC,57.750556,-152.468612,C,REC,1,50.0,CL1,WOWL,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15515,20240516194270,SUBS,NONE,SUBS-NONE,2800.0,NaN,Fr,1630.0,2024,5,...,VMC,45.878111,-111.569440,NaN,NaN,1,77.0,CL3,WOWL,NaN
15516,20240519194280,SUBS,MINR,SUBS-MINR,12500.0,19.0,Sa,1830.0,2024,5,...,VMC,40.941560,-82.863440,NaN,NaN,1,51.0,CL1,WOWL,NaN
15517,20240520194283,SUBS,NONE,SUBS-NONE,2200.0,7.6,We,2230.0,2024,5,...,VMC,29.727974,-96.060159,NaN,NaN,1,56.0,CL3,WWL,NaN
15518,20240526194310,SUBS,NONE,SUBS-NONE,3600.0,NaN,Mo,1730.0,2024,3,...,VMC,33.227006,-84.274975,NaN,NaN,1,39.0,CL2,WOWL,NaN
15519,20240531194353,SUBS,NONE,SUBS-NONE,3600.0,NaN,Th,1617.0,2024,5,...,VMC,27.642597,-82.519917,NaN,NaN,1,62.0,CL3,WOWL,NaN